### ISSUE TITLE
Collator authors block #1 repeatedly, chain does not grow.

### ISSUE THREAD

**Issue by JoshOrndorff** [KILTprotocol/kilt-parachain#2]
When I start a relay chain and parachain as described in the readme, I'm able to start all the nodes and they all peer together. I submit the registration transaction and I believe it succeeds because the collator begins authoring blocks. However it quthors block #1 over and over, and the best block never increases.

I've live streamed my process from start to finish to help you diagnose the issue, and I hope you might look it over for clues about the behavior or mistakes on my part. https://www.twitch.tv/videos/800633070

**Comment by JoshOrndorff** [comment]
The recording is at https://www.twitch.tv/videos/800633070 I'll edit it into the main issue too.

**Comment by JoshOrndorff** [comment]
Thanks to suggestion from @bkchr, running the nodes with `--discover-local` and being patient for ~10minutes allows the collator to start collating. I don't yet understand that flag or authority discovery in general very well, so I'm not sure why or how it works.

**Comment by wischli** [comment]
I just updated and checked with latest master versions (see Readme) and it worked for me without `discover-local` and much faster than 10 minutes. Anyway, I added this to the Readme in 65c488fd16fa07b9e978ad85118b10ea59e6fa8e. Thanks a lot and I hope your Moonbeam parachain now also builds blocks 🌚
